package cs555.hw1.wireformats;

public interface Protocol {
    int CLIENT_REQUESTS_CHUNK_SERVERS_FROM_CONTROLLER = 2;
    int CONTROLLER_SENDS_CLIENT_CHUNK_SERVERS = 3;
    int REGISTER_CLIENT = 4;
    int REPORT_CLIENT_REGISTRATION = 5;
    int REGISTER_CHUNK_SERVER = 6;
    int REPORT_CHUNK_SERVER_REGISTRATION = 7;
    int STORE_CHUNK = 8;
    int SEND_MAJOR_HEARTBEAT = 9;
    int SEND_MINOR_HEARTBEAT = 10;
    int RETRIEVE_FILE_REQUEST = 11;
    int RETRIEVE_FILE_RESPONSE = 12;
    int REPORT_FILE_CORRUPTION = 13;
    int SEND_FILE_INFO = 14;
    int RETRIEVE_CHUNK_REQUEST = 15;
    int RETRIEVE_CHUNK_RESPONSE = 16;
    int REPORT_CHUNK_CORRUPTION = 17;
    int FIX_CORRUPT_CHUNK = 18;
}
